<?php

/**
 * @file
 * Contains drupal_tube_layouts.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function drupal_tube_layouts_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the drupal_tube_layouts module.
    case 'help.page.drupal_tube_layouts':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Creates new layouts for layout builder') . '</p>';
      return $output;

    default:
  }
}
