<?php

/**
 * Implements hook_preprocess_layout().
 */
function drupal_tube_layouts_preprocess_layout(&$variables) {
  $current_route = \Drupal::routeMatch();
  $node = $current_route->getParameters()->get('node');
  if (!empty($node)) {
    if ($node->bundle() == 'conference') {
      $hero_media_image = $node->get('field_hero_image');
      if (!$hero_media_image->isEmpty()) {
        $uri = $hero_media_image->entity->get('field_media_image')->entity->uri->value;
        $variables['background_image_url'] = file_create_url($uri);
      }
    }
  }
}
  