<?php

/**
 * @file
 * Contains drupal_tube_layouts.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function drupal_tube_layouts_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the drupal_tube_layouts module.
    case 'help.page.drupal_tube_layouts':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Creates new layouts for layout builder') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_layout().
 */
function drupal_tube_layouts_preprocess_layout(&$variables) {
  if (isset($variables['settings'])) {
/*
    if (is_subclass_of($variables['layout']->getClass(), '\Drupal\drupal_tube_layouts\LayoutPreprocessInterface')) {
      $class = $variables['layout']->getClass();
      $class::preprocess($variables);
    }
    */
    if (!empty($variables['settings']['bgcolor'])) {
      $variables['attributes']['class'][] = $variables['settings']['bgcolor'];
    }
  }
}
